const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding FITTRACK AI standard exercise library, food database, and challenges...");

  // Seed Exercises
  const exercises = [
    {
      name: "Barbell Bench Press",
      normalizedName: "barbell-bench-press",
      category: "Chest",
      primaryMuscle: "Chest (Pectoralis Major)",
      secondaryMuscles: "Triceps, Front Deltoids",
      equipment: "Barbell",
      difficulty: "Intermediate",
      instructions: "Lie flat on the bench with feet planted firmly on the floor. Grip the barbell slightly wider than shoulder-width. Lower the bar smoothly to your mid-chest while keeping elbows at ~45-75 degrees. Press back upward explosively to full extension without locking elbows violently.",
      tips: "Keep shoulder blades retracted and depressed. Drive through heels.",
      commonMistakes: "Bouncing bar off chest, flaring elbows out to 90 degrees, lifting hips off bench.",
      defaultSets: 4,
      defaultReps: 8,
      restSeconds: 120,
      imageUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80",
    },
    {
      name: "Incline Dumbbell Press",
      normalizedName: "incline-dumbbell-press",
      category: "Chest",
      primaryMuscle: "Upper Chest (Clavicular Head)",
      secondaryMuscles: "Front Deltoids, Triceps",
      equipment: "Dumbbell",
      difficulty: "Intermediate",
      instructions: "Set bench angle to 30-45 degrees. Hold dumbbells at chest height, palms forward. Press upward until arms are straight, keeping a controlled arc.",
      tips: "Keep wrist stacked over elbows.",
      commonMistakes: "Setting bench angle too steep (over 45 degrees shifts work to shoulders).",
      defaultSets: 3,
      defaultReps: 10,
      restSeconds: 90,
      imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80",
    },
    {
      name: "Cable Chest Fly",
      normalizedName: "cable-chest-fly",
      category: "Chest",
      primaryMuscle: "Chest",
      secondaryMuscles: "Front Deltoids",
      equipment: "Cable",
      difficulty: "Beginner",
      instructions: "Position pulleys at chest height. Take a step forward, bend elbows slightly, and bring handles together in an hugging motion. Squeeze chest for 1 second at peak contraction.",
      tips: "Maintain slight elbow bend throughout the entire motion.",
      commonMistakes: "Straightening and bending arms dynamically turning it into a press.",
      defaultSets: 3,
      defaultReps: 12,
      restSeconds: 60,
      imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80",
    },
    {
      name: "Barbell Squat",
      normalizedName: "barbell-squat",
      category: "Legs",
      primaryMuscle: "Quadriceps",
      secondaryMuscles: "Glutes, Hamstrings, Core, Spinal Erectors",
      equipment: "Barbell",
      difficulty: "Advanced",
      instructions: "Rest barbell across upper traps (high bar) or rear delts (low bar). Stand with feet shoulder-width, toes slightly flared. Brace core, break at hips and knees simultaneously, descend until thighs are at or below parallel. Drive up through midfoot.",
      tips: "Inhale and brace core using the Valsalva maneuver before descent.",
      commonMistakes: "Knees caving inward (valgus collapse), leaning too far forward, heel rising.",
      defaultSets: 4,
      defaultReps: 6,
      restSeconds: 150,
      imageUrl: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&auto=format&fit=crop&q=80",
    },
    {
      name: "Romanian Deadlift (RDL)",
      normalizedName: "romanian-deadlift",
      category: "Legs",
      primaryMuscle: "Hamstrings",
      secondaryMuscles: "Glutes, Lower Back, Lats",
      equipment: "Barbell",
      difficulty: "Intermediate",
      instructions: "Stand tall holding barbell at hip width. Soften knees slightly. Hinge backwards at hips, sending glutes toward the wall behind you. Keep spine neutral and bar close to legs. Reverse motion when deep stretch is felt in hamstrings.",
      tips: "The movement is a pure hip hinge, not a squat.",
      commonMistakes: "Rounding the lumbar spine, squatting down instead of hinging hips back.",
      defaultSets: 3,
      defaultReps: 10,
      restSeconds: 90,
      imageUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80",
    },
    {
      name: "Pull-ups",
      normalizedName: "pull-ups",
      category: "Back",
      primaryMuscle: "Latissimus Dorsi",
      secondaryMuscles: "Biceps, Rear Deltoids, Traps",
      equipment: "Bodyweight",
      difficulty: "Intermediate",
      instructions: "Grip pull-up bar overhand slightly wider than shoulders. Hang at full extension. Depress shoulder blades and pull chest up toward the bar until chin clears the bar. Lower with control.",
      tips: "Engage lats first by pulling shoulders down before bending elbows.",
      commonMistakes: "Kicking legs, partial reps, craning neck over bar.",
      defaultSets: 3,
      defaultReps: 8,
      restSeconds: 90,
      imageUrl: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&auto=format&fit=crop&q=80",
    },
    {
      name: "Barbell Bent-Over Row",
      normalizedName: "barbell-bent-over-row",
      category: "Back",
      primaryMuscle: "Upper Back & Lats",
      secondaryMuscles: "Biceps, Posterior Deltoid, Lower Back",
      equipment: "Barbell",
      difficulty: "Intermediate",
      instructions: "Hinge at hips to a 45-degree angle with neutral back. Grip bar slightly wider than shoulder width. Pull the barbell up towards your lower ribcage / navel, squeezing shoulder blades together at the top.",
      tips: "Pull with your elbows, not your hands.",
      commonMistakes: "Using excessive body momentum / standing up during row, rounding back.",
      defaultSets: 4,
      defaultReps: 8,
      restSeconds: 90,
      imageUrl: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&auto=format&fit=crop&q=80",
    },
    {
      name: "Overhead Dumbbell Shoulder Press",
      normalizedName: "overhead-dumbbell-shoulder-press",
      category: "Shoulders",
      primaryMuscle: "Anterior & Lateral Deltoids",
      secondaryMuscles: "Triceps, Upper Traps",
      equipment: "Dumbbell",
      difficulty: "Beginner",
      instructions: "Sit upright or stand with dumbbells at shoulder level, elbows beneath wrists. Press weights vertically overhead until arms are extended. Lower under control to ear height.",
      tips: "Do not arch lower back excessively; keep core braced.",
      commonMistakes: "Flaring elbows too far back behind coronal plane.",
      defaultSets: 3,
      defaultReps: 10,
      restSeconds: 90,
      imageUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=600&auto=format&fit=crop&q=80",
    },
    {
      name: "Dumbbell Lateral Raise",
      normalizedName: "dumbbell-lateral-raise",
      category: "Shoulders",
      primaryMuscle: "Lateral Deltoids",
      secondaryMuscles: "Supraspinatus, Traps",
      equipment: "Dumbbell",
      difficulty: "Beginner",
      instructions: "Stand with dumbbells at sides. Raise dumbbells out to sides with slight bend in elbows until arms are parallel to the floor. Pour water feeling at top. Lower slowly.",
      tips: "Lead with elbows, keep thumbs slightly lower than pinkies.",
      commonMistakes: "Using body swing / swinging weights with hips.",
      defaultSets: 4,
      defaultReps: 15,
      restSeconds: 60,
      imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80",
    },
    {
      name: "Tricep Rope Pushdown",
      normalizedName: "tricep-rope-pushdown",
      category: "Triceps",
      primaryMuscle: "Triceps Brachii",
      secondaryMuscles: "Forearms",
      equipment: "Cable",
      difficulty: "Beginner",
      instructions: "Attach rope to high cable pulley. Keep elbows pinned to sides. Extend arms downward, flaring the rope outward at bottom for peak contraction.",
      tips: "Lock elbows in space; do not allow upper arm to swing forward.",
      commonMistakes: "Leaning heavily over rope and pushing with chest.",
      defaultSets: 3,
      defaultReps: 12,
      restSeconds: 60,
      imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80",
    },
    {
      name: "Incline Dumbbell Bicep Curl",
      normalizedName: "incline-dumbbell-bicep-curl",
      category: "Biceps",
      primaryMuscle: "Biceps Brachii (Long Head)",
      secondaryMuscles: "Brachialis",
      equipment: "Dumbbell",
      difficulty: "Beginner",
      instructions: "Lie back on 60-degree incline bench, arms hanging straight down. Curl dumbbells up while supinating wrists (palms facing up). Squeeze biceps at top, lower slowly to full stretch.",
      tips: "The stretch at the bottom activates the long head of the bicep intensely.",
      commonMistakes: "Swinging elbows forward away from vertical plane.",
      defaultSets: 3,
      defaultReps: 12,
      restSeconds: 60,
      imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600&auto=format&fit=crop&q=80",
    },
    {
      name: "Hanging Leg Raise",
      normalizedName: "hanging-leg-raise",
      category: "Core",
      primaryMuscle: "Rectus Abdominis",
      secondaryMuscles: "Hip Flexors, Forearms (Grip)",
      equipment: "Bodyweight",
      difficulty: "Intermediate",
      instructions: "Hang from pull-up bar with overhand grip. Engage core, flex hips and knees or keep legs straight, raising feet toward hip or chest height without swinging.",
      tips: "Curl pelvis upward at top of rep to emphasize abdominal contraction.",
      commonMistakes: "Using momentum and swinging body like a pendulum.",
      defaultSets: 3,
      defaultReps: 12,
      restSeconds: 60,
      imageUrl: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&auto=format&fit=crop&q=80",
    }
  ];

  for (const ex of exercises) {
    await prisma.exercise.upsert({
      where: { normalizedName: ex.normalizedName },
      update: ex,
      create: ex,
    });
  }

  // Seed Foods (Nutritional values per 100g standard basis)
  const foods = [
    // South Indian
    {
      name: "Idli",
      canonicalName: "idli",
      category: "South Indian",
      defaultServingSize: 60, // 1 idli ~ 50-60g
      defaultServingUnit: "piece",
      calories: 140, // per 100g (~2 idlis)
      protein: 4.8,
      carbs: 28.0,
      fat: 0.6,
      fiber: 2.1,
      sugar: 0.2,
      sodium: 180,
    },
    {
      name: "Dosa (Plain)",
      canonicalName: "dosa-plain",
      category: "South Indian",
      defaultServingSize: 100, // 1 medium dosa
      defaultServingUnit: "piece",
      calories: 168,
      protein: 3.9,
      carbs: 29.0,
      fat: 3.7,
      fiber: 1.5,
      sugar: 0.4,
      sodium: 210,
    },
    {
      name: "Sambar",
      canonicalName: "sambar",
      category: "South Indian",
      defaultServingSize: 150,
      defaultServingUnit: "ml",
      calories: 65, // per 100g
      protein: 2.8,
      carbs: 9.5,
      fat: 1.8,
      fiber: 2.4,
      sugar: 1.5,
      sodium: 320,
    },
    {
      name: "Coconut Chutney",
      canonicalName: "coconut-chutney",
      category: "South Indian",
      defaultServingSize: 30,
      defaultServingUnit: "g",
      calories: 220, // per 100g
      protein: 3.2,
      carbs: 6.8,
      fat: 21.0,
      fiber: 4.2,
      sugar: 1.8,
      sodium: 280,
    },
    {
      name: "Medu Vada",
      canonicalName: "medu-vada",
      category: "South Indian",
      defaultServingSize: 50,
      defaultServingUnit: "piece",
      calories: 275, // per 100g
      protein: 9.2,
      carbs: 24.5,
      fat: 16.0,
      fiber: 3.8,
      sugar: 0.2,
      sodium: 310,
    },
    {
      name: "Curd Rice",
      canonicalName: "curd-rice",
      category: "South Indian",
      defaultServingSize: 200,
      defaultServingUnit: "g",
      calories: 145, // per 100g
      protein: 3.6,
      carbs: 23.0,
      fat: 4.2,
      fiber: 0.8,
      sugar: 2.2,
      sodium: 240,
    },
    {
      name: "Ven Pongal",
      canonicalName: "ven-pongal",
      category: "South Indian",
      defaultServingSize: 180,
      defaultServingUnit: "g",
      calories: 185,
      protein: 4.5,
      carbs: 26.5,
      fat: 6.8,
      fiber: 2.1,
      sugar: 0.1,
      sodium: 260,
    },
    // North Indian & Staples
    {
      name: "Chapati / Roti (Whole Wheat)",
      canonicalName: "chapati-whole-wheat",
      category: "North Indian",
      defaultServingSize: 40, // 1 medium roti
      defaultServingUnit: "piece",
      calories: 264, // per 100g (approx 2.5 rotis)
      protein: 8.5,
      carbs: 52.0,
      fat: 2.8,
      fiber: 7.2,
      sugar: 1.0,
      sodium: 150,
    },
    {
      name: "Dal Tadka (Yellow Lentils)",
      canonicalName: "dal-tadka",
      category: "North Indian",
      defaultServingSize: 180,
      defaultServingUnit: "g",
      calories: 115,
      protein: 6.2,
      carbs: 15.4,
      fat: 3.2,
      fiber: 3.8,
      sugar: 0.8,
      sodium: 290,
    },
    {
      name: "Paneer Butter Masala",
      canonicalName: "paneer-butter-masala",
      category: "North Indian",
      defaultServingSize: 200,
      defaultServingUnit: "g",
      calories: 210,
      protein: 7.8,
      carbs: 8.2,
      fat: 16.5,
      fiber: 1.8,
      sugar: 3.5,
      sodium: 410,
    },
    {
      name: "Palak Paneer",
      canonicalName: "palak-paneer",
      category: "North Indian",
      defaultServingSize: 200,
      defaultServingUnit: "g",
      calories: 160,
      protein: 8.2,
      carbs: 6.0,
      fat: 12.0,
      fiber: 3.1,
      sugar: 1.2,
      sodium: 350,
    },
    {
      name: "Chole / Chickpea Curry",
      canonicalName: "chole-curry",
      category: "North Indian",
      defaultServingSize: 200,
      defaultServingUnit: "g",
      calories: 150,
      protein: 6.5,
      carbs: 21.0,
      fat: 4.6,
      fiber: 5.5,
      sugar: 2.1,
      sodium: 380,
    },
    {
      name: "Rajma (Kidney Beans Curry)",
      canonicalName: "rajma-curry",
      category: "North Indian",
      defaultServingSize: 200,
      defaultServingUnit: "g",
      calories: 142,
      protein: 7.1,
      carbs: 20.2,
      fat: 3.8,
      fiber: 5.2,
      sugar: 1.9,
      sodium: 360,
    },
    {
      name: "White Basmati Rice (Cooked)",
      canonicalName: "white-basmati-rice-cooked",
      category: "Grains",
      defaultServingSize: 150,
      defaultServingUnit: "g",
      calories: 130,
      protein: 2.7,
      carbs: 28.2,
      fat: 0.3,
      fiber: 0.4,
      sugar: 0.1,
      sodium: 5,
    },
    {
      name: "Brown Rice (Cooked)",
      canonicalName: "brown-rice-cooked",
      category: "Grains",
      defaultServingSize: 150,
      defaultServingUnit: "g",
      calories: 123,
      protein: 2.7,
      carbs: 25.6,
      fat: 1.0,
      fiber: 1.8,
      sugar: 0.2,
      sodium: 4,
    },
    // Non-Veg & High Protein Staples
    {
      name: "Chicken Biryani",
      canonicalName: "chicken-biryani",
      category: "Non-Veg",
      defaultServingSize: 300,
      defaultServingUnit: "g",
      calories: 180, // per 100g
      protein: 9.8,
      carbs: 22.4,
      fat: 5.8,
      fiber: 1.4,
      sugar: 0.8,
      sodium: 390,
    },
    {
      name: "Chicken Breast (Grilled / Cooked)",
      canonicalName: "chicken-breast-grilled",
      category: "Protein",
      defaultServingSize: 150,
      defaultServingUnit: "g",
      calories: 165,
      protein: 31.0,
      carbs: 0.0,
      fat: 3.6,
      fiber: 0.0,
      sugar: 0.0,
      sodium: 74,
    },
    {
      name: "Whole Boiled Egg",
      canonicalName: "whole-boiled-egg",
      category: "Protein",
      defaultServingSize: 50, // 1 large egg
      defaultServingUnit: "piece",
      calories: 155, // per 100g (~2 eggs)
      protein: 13.0,
      carbs: 1.1,
      fat: 11.0,
      fiber: 0.0,
      sugar: 0.8,
      sodium: 124,
    },
    {
      name: "Egg Whites (Cooked)",
      canonicalName: "egg-whites-cooked",
      category: "Protein",
      defaultServingSize: 100,
      defaultServingUnit: "g",
      calories: 52,
      protein: 11.0,
      carbs: 0.7,
      fat: 0.2,
      fiber: 0.0,
      sugar: 0.7,
      sodium: 166,
    },
    {
      name: "Tandoori Chicken",
      canonicalName: "tandoori-chicken",
      category: "Non-Veg",
      defaultServingSize: 180,
      defaultServingUnit: "g",
      calories: 175,
      protein: 24.5,
      carbs: 3.2,
      fat: 7.1,
      fiber: 0.6,
      sugar: 0.5,
      sodium: 480,
    },
    {
      name: "Fish Curry (South Indian / Bengali)",
      canonicalName: "fish-curry",
      category: "Non-Veg",
      defaultServingSize: 200,
      defaultServingUnit: "g",
      calories: 135,
      protein: 14.8,
      carbs: 4.2,
      fat: 6.8,
      fiber: 0.9,
      sugar: 0.7,
      sodium: 390,
    },
    {
      name: "Whey Protein Powder (1 Scoop)",
      canonicalName: "whey-protein-powder",
      category: "Protein",
      defaultServingSize: 32, // 1 scoop
      defaultServingUnit: "g",
      calories: 390, // per 100g (~125 kcal per 32g scoop)
      protein: 78.0, // ~25g per scoop
      carbs: 6.5,
      fat: 5.0,
      fiber: 1.0,
      sugar: 3.0,
      sodium: 160,
    },
    {
      name: "Paneer (Raw / Cottage Cheese)",
      canonicalName: "paneer-raw",
      category: "Dairy",
      defaultServingSize: 100,
      defaultServingUnit: "g",
      calories: 296,
      protein: 18.3,
      carbs: 3.4,
      fat: 22.0,
      fiber: 0.0,
      sugar: 2.8,
      sodium: 30,
    },
    {
      name: "Greek Yogurt (Plain)",
      canonicalName: "greek-yogurt-plain",
      category: "Dairy",
      defaultServingSize: 150,
      defaultServingUnit: "g",
      calories: 97,
      protein: 9.0,
      carbs: 3.6,
      fat: 5.0,
      fiber: 0.0,
      sugar: 3.6,
      sodium: 45,
    },
    {
      name: "Rolled Oats (Dry)",
      canonicalName: "rolled-oats-dry",
      category: "Grains",
      defaultServingSize: 50,
      defaultServingUnit: "g",
      calories: 389,
      protein: 16.9,
      carbs: 66.3,
      fat: 6.9,
      fiber: 10.6,
      sugar: 0.9,
      sodium: 2,
    },
    {
      name: "Banana",
      canonicalName: "banana",
      category: "Fruits",
      defaultServingSize: 118, // 1 medium banana
      defaultServingUnit: "piece",
      calories: 89,
      protein: 1.1,
      carbs: 22.8,
      fat: 0.3,
      fiber: 2.6,
      sugar: 12.2,
      sodium: 1,
    },
    {
      name: "Almonds (Raw)",
      canonicalName: "almonds-raw",
      category: "Snacks",
      defaultServingSize: 28, // 1 oz
      defaultServingUnit: "g",
      calories: 579,
      protein: 21.2,
      carbs: 21.6,
      fat: 49.9,
      fiber: 12.5,
      sugar: 4.4,
      sodium: 1,
    },
    {
      name: "Vegetable Raita",
      canonicalName: "vegetable-raita",
      category: "Dairy",
      defaultServingSize: 100,
      defaultServingUnit: "g",
      calories: 68,
      protein: 3.2,
      carbs: 4.8,
      fat: 3.8,
      fiber: 0.6,
      sugar: 3.5,
      sodium: 180,
    }
  ];

  for (const food of foods) {
    const createdFood = await prisma.food.upsert({
      where: { canonicalName: food.canonicalName },
      update: {
        name: food.name,
        category: food.category,
        defaultServingSize: food.defaultServingSize,
        defaultServingUnit: food.defaultServingUnit,
      },
      create: {
        name: food.name,
        canonicalName: food.canonicalName,
        category: food.category,
        defaultServingSize: food.defaultServingSize,
        defaultServingUnit: food.defaultServingUnit,
      },
    });

    await prisma.foodNutrition.upsert({
      where: { foodId: createdFood.id },
      update: {
        calories: food.calories,
        protein: food.protein,
        carbs: food.carbs,
        fat: food.fat,
        fiber: food.fiber,
        sugar: food.sugar,
        sodium: food.sodium,
      },
      create: {
        foodId: createdFood.id,
        servingBasis: 100,
        calories: food.calories,
        protein: food.protein,
        carbs: food.carbs,
        fat: food.fat,
        fiber: food.fiber,
        sugar: food.sugar,
        sodium: food.sodium,
      },
    });
  }

  // Seed Challenges
  const challenges = [
    {
      title: "30-Day Strength Consistency",
      description: "Log 20 completed workout sessions in 30 days to build unbreakable workout discipline.",
      category: "workouts",
      metric: "workouts",
      targetValue: 20,
      badgeIcon: "Trophy",
      startDate: new Date(),
      endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Hydration Master (7-Day Sprint)",
      description: "Hit your daily 3,000 ml water target for 7 consecutive days.",
      category: "hydration",
      metric: "ml",
      targetValue: 21000,
      badgeIcon: "Droplets",
      startDate: new Date(),
      endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    },
    {
      title: "Macro Discipline Sprint",
      description: "Hit your daily protein target for 14 active days.",
      category: "nutrition",
      metric: "days",
      targetValue: 14,
      badgeIcon: "Flame",
      startDate: new Date(),
      endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    },
  ];

  for (const c of challenges) {
    const existing = await prisma.challenge.findFirst({
      where: { title: c.title },
    });
    if (!existing) {
      await prisma.challenge.create({ data: c });
    }
  }

  // Create standard Workout Plan: Push Pull Legs
  const pushExercises = await prisma.exercise.findMany({
    where: { category: { in: ["Chest", "Shoulders", "Triceps"] } },
    take: 4,
  });

  const pplPlan = await prisma.workoutPlan.upsert({
    where: { id: "standard-ppl-plan" },
    update: {},
    create: {
      id: "standard-ppl-plan",
      title: "Push Pull Legs (PPL) - Hypertrophy",
      description: "The gold standard 6-day split designed for balanced muscle hypertrophy, strength progression, and optimal recovery.",
      level: "Intermediate",
      daysPerWeek: 6,
      days: {
        create: [
          {
            dayOfWeek: 1,
            name: "Push Day (Chest, Shoulders, Triceps)",
            isRestDay: false,
            exercises: {
              create: pushExercises.map((e, idx) => ({
                exerciseId: e.id,
                orderIndex: idx,
                targetSets: 4,
                targetReps: "8-12",
                restSeconds: 90,
              })),
            },
          },
          {
            dayOfWeek: 2,
            name: "Pull Day (Back, Rear Delts, Biceps)",
            isRestDay: false,
          },
          {
            dayOfWeek: 3,
            name: "Legs Day (Quads, Hamstrings, Calves)",
            isRestDay: false,
          },
          {
            dayOfWeek: 4,
            name: "Rest & Active Recovery",
            isRestDay: true,
          },
          {
            dayOfWeek: 5,
            name: "Push Day (Volume Focus)",
            isRestDay: false,
          },
          {
            dayOfWeek: 6,
            name: "Pull Day (Volume Focus)",
            isRestDay: false,
          },
          {
            dayOfWeek: 7,
            name: "Full Rest Day",
            isRestDay: true,
          },
        ],
      },
    },
  });

  console.log("Seeding completed successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
